apiVersion: apps/v1 
kind: Deployment
metadata:
  name: postgre
spec: 
  selector: 
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:14.3
        ports:
          - containerPort: 5432
        env: 
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_DB
          value: "kubenews"

---
apiVersion: v1
kind: Service
metadata:
  name:  svc-postgre
spec:
  selector:
    app:  postgre
  ports:
  - port: 5432
    targetPort:  5432
        
